#! /bin/sh

sxhkd &

bspc monitor -d web term chat music code code code 6 7

bspc config border_width 7
bspc config window_gap 45
bspc config top_padding	0
bspc config bottom_padding  0
bspc config focused_border_color "#FF9292"
bspc config normal_border_color "#FCF5DD"

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_by_distance true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Google-chrome desktop=^1
bspc rule -a Firefox desktop=^1
bspc rule -a Genymotion desktop=^3
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Atom desktop=^5
bspc rule -a Spotify desktop=^4
bspc rule -a Lmms desktop=^5
bspc rule -a mplayer2 state=floating
bspc rule -a Gedit state=floating
bspc rule -a Eog state=floating
# bspc rule -a Nautilus state=floating
bspc rule -a File-roller state=floating
bspc rule -a Gnome-system-monitor state=floating
bspc rule -a feh floating=on
bspc rule -a vlc floating=on
bspc rule -a mpv floating=on
bspc rule -a jetbrains-idea-ce desktop=^6
bspc rule -a com.oracle.javafx.scenebuilder.app.SceneBuilderApp desktop=^7
bspc rule -a Enpass-Desktop state=floating
bspc rule -a tatai.app.Main state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
# bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name left_ptr

feh --bg-fill ~/Pictures/Wallpapers/7SqL0BC.jpg
#gnome-wallpaper-changer &
compton --config ~/compton.conf -b
#xrdb -merge ~/.Xdefaults
redshift &
#/home/gamehelp16/allfloat.sh &
compton &

#panel &
polybar top

wmname LG3D
